# Use the official Go image as the base image
FROM golang:1.19

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application files to the container's working directory
COPY . .

# Build the Go application
RUN go build -o myapp .

CMD ["sh", "-c", "ls && ./myapp"]

